# Generated by Django 5.2.7 on 2025-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('style', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='dz/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
